<?php $this->plugin('translate')->setTranslatorTextDomain('playgroundsales');// Pour le texte ?>
<h2><?php echo $this->translate('Order list') ?></h2>
<table class="table">
    <thead>
        <tr>
            <th><?php echo $this->translate('Amount') ?></th>
            <th><?php echo $this->translate('First name') ?></th>
            <th><?php echo $this->translate('Last name') ?></th>
            <th><?php echo $this->translate('Email') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($this->orders as $order):?>
        <tr>
            <td><?php echo $this->currencyFormat( $order->getAmount(), $order->getCurrency()->getSymbol()) ; ?></td>
            <?php $user = $order->getUser() ?>
            <td><?php echo $user ? $user->getFirstname() : ''; ?></td>
            <td><?php echo $user ? $user->getLastname() : ''; ?></td>
            <td><?php echo $user ? $user->getEmail() : ''; ?></td>
        </tr>
    <?php endforeach;?>
    </tbody>
</table>

