<?php
$this->plugin('translate')->setTranslatorTextDomain('playgroundsales');
$form = $this->form;
$form->prepare();
?>

<?php echo $this->form()->openTag($form) ?>
    <?php echo $this->formHidden($form->get('id')); ?>
    <fieldset>
        <div class="label-input">
            <?php echo $this->formLabel($form->get('className')); ?>
            <?php echo $this->formInput($form->get('className')); ?>
            <?php echo $this->formElementErrors($form->get('className')); ?>
        </div>
        <div class="label-input">
            <?php echo $this->formLabel($form->get('name')); ?>
            <?php echo $this->formInput($form->get('name')); ?>
            <?php echo $this->formElementErrors($form->get('name')); ?>
        </div>
        <div class="label-input">
            <?php echo $this->formLabel($form->get('valid')); ?>
            <?php echo $this->formCheckbox($form->get('valid')); ?>
            <?php echo $this->formElementErrors($form->get('valid')); ?>
        </div>
    </fieldset>
<?php echo $this->formButton($form->get('submit')); ?>
<?php echo $this->form()->closeTag() ?>